export const AUTH_LOGIN ="AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS ="AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILD ="AUTH_LOGIN_FAILD";

export const AUTH_SIGNUP ="AUTH_SIGNUP";
export const AUTH_SIGNUP_SUCCESS ="AUTH_SIGNUP_SUCCESS";
export const AUTH_SIGNUP_FAILD ="AUTH_SIGNUP_FAILD";


export const ON_BUTTON_SUBMIT ="ON_BUTTON_SUBMIT";
export const OFF_BUTTON_SUBMIT ="OFF_BUTTON_SUBMIT";

export const CHECK_AUTH_SUCCESS ="CHECK_AUTH_SUCCESS";
export const CHECK_AUTH_FAILD ="CHECK_AUTH_FAILD";

export const FETCH_USER ="FETCH_USER";
export const FETCH_USER_FAILED ="FETCH_USER_FAILED";
export const FETCH_USER_SUCCESS ="FETCH_USER_SUCCESS";

export const UPDATE_USER="UPDATE_USER";
export const UPDATE_USER_FAILED="UPDATE_USER_FAILED";
export const UPDATE_USER_SUCCESS="UPDATE_USER_SUCCESS";

export const SET_USER_DELETE ="SET_USER_DELETE";
export const SET_USER_DELETE_FAILED ="SET_USER_DELETE_FAILED";
export const SET_USER_DELETE_SUCCESS ="SET_USER_DELETE_SUCCESS";


export const SET_USER_EDITING = "SET_USER_EDITING";