
// api main
export const REFESH_MAIN ='REFESH_MAIN';
export const REFESH_MAIN_SUCCESS = 'REFESH_MAIN_SUCCESS';
export const REFESH_MAIN_FAILED = 'REFESH_MAIN_FAILED';

// api house_erea
export const REFESH_HOUSE_AREA ='REFESH_HOUSE_AREA';
export const REFESH_HOUSE_AREA_SUCCESS = 'REFESH_HOUSE_AREA_SUCCESS';
export const REFESH_HOUSE_AREA_FAILED = 'REFESH_HOUSE_AREA_FAILED';

export const REFESH_POWER_HOUSE_AREA ='REFESH_POWER_HOUSE_AREA';
export const REFESH_POWER_HOUSE_AREA_SUCCESS = 'REFESH_POWER_HOUSE_AREA_SUCCESS';
export const REFESH_POWER_HOUSE_AREA_FAILED = 'REFESH_POWER_HOUSE_AREA_FAILED';

// api fish_lake_erea
export const REFESH_FISH_LAKE_AREA ='REFESH_FISH_LAKE_AREA';
export const REFESH_FISH_LAKE_AREA_SUCCESS = 'REFESH_FISH_LAKE_AREA_SUCCESS';
export const REFESH_FISH_LAKE_AREA_FAILED = 'REFESH_FISH_LAKE_AREA_FAILED';

export const REFESH_POWER_FISH_LAKE_AREA ='REFESH_POWER_FISH_LAKE_AREA';
export const REFESH_POWER_FISH_LAKE_AREA_SUCCESS = 'REFESH_POWER_FISH_LAKE_AREA_SUCCESS';
export const REFESH_POWER_FISH_LAKE_AREA_FAILED = 'REFESH_POWER_FISH_LAKE_AREA_FAILED';

// api solar_01_erea
export const REFESH_SOLAR01_AREA ='REFESH_SOLAR01_AREA';
export const REFESH_SOLAR01_AREA_SUCCESS = 'REFESH_SOLAR01_AREA_SUCCESS';
export const REFESH_SOLAR01_AREA_FAILED = 'REFESH_SOLAR01_AREA_FAILED';

export const REFESH_POWER_SOLAR01_AREA ='REFESH_POWER_SOLAR01_AREA';
export const REFESH_POWER_SOLAR01_AREA_SUCCESS = 'REFESH_POWER_SOLAR01_AREA_SUCCESS';
export const REFESH_POWER_SOLAR01_AREA_FAILED = 'REFESH_POWER_SOLAR01_AREA_FAILED';

// api solar_02_erea
export const REFESH_SOLAR02_AREA ='REFESH_SOLAR02_AREA';
export const REFESH_SOLAR02_AREA_SUCCESS = 'REFESH_SOLAR02_AREA_SUCCESS';
export const REFESH_SOLAR02_AREA_FAILED = 'REFESH_SOLAR02_AREA_FAILED';

export const REFESH_POWER_SOLAR02_AREA ='REFESH_POWER_SOLAR02_AREA';
export const REFESH_POWER_SOLAR02_AREA_SUCCESS = 'REFESH_POWER_SOLAR02_AREA_SUCCESS';
export const REFESH_POWER_SOLAR02_AREA_FAILED = 'REFESH_POWER_SOLAR02_AREA_FAILED';