// api temp humi 
export const REFESH_TEMPHUMI ='REFESH_TEMPHUMI';
export const REFESH_TEMPHUMI_SUCCESS = 'REFESH_TEMPHUMI_SUCCESS';
export const REFESH_TEMPHUMI_FAILED = 'REFESH_TEMPHUMI_FAILED';

// api ups
export const REFESH_UPS ='REFESH_UPS';
export const REFESH_UPS_SUCCESS = 'REFESH_UPS_SUCCESS';
export const REFESH_UPS_FAILED = 'REFESH_UPS_FAILED';

export const REFESH_UPSPOWER ='REFESH_UPSPOWER';
export const REFESH_UPSPOWER_SUCCESS = 'REFESH_UPSPOWER_SUCCESS';
export const REFESH_UPSPOWER_FAILED = 'REFESH_UPSPOWER_FAILED';

// api pmu
export const REFESH_PMU ='REFESH_PMU';
export const REFESH_PMU_SUCCESS = 'REFESH_PMU_SUCCESS';
export const REFESH_PMU_FAILED = 'REFESH_PMU_FAILED';

export const REFESH_PMUPOWER ='REFESH_PMUPOWER';
export const REFESH_PMUPOWER_SUCCESS = 'REFESH_PMUPOWER_SUCCESS';
export const REFESH_PMUPOWER_FAILED = 'REFESH_PMUPOWER_FAILED';

// api air
export const REFESH_AIR ='REFESH_AIR';
export const REFESH_AIR_SUCCESS = 'REFESH_AIR_SUCCESS';
export const REFESH_AIR_FAILED = 'REFESH_AIR_FAILED';

export const REFESH_AIRPOWER ='REFESH_AIRPOWER';
export const REFESH_AIRPOWER_SUCCESS = 'REFESH_AIRPOWER_SUCCESS';
export const REFESH_AIRPOWER_FAILED = 'REFESH_AIRPOWER_FAILED';

export const REFESH_AIRSETTING ='REFESH_AIRSETTING';
export const REFESH_AIRSETTING_SUCCESS = 'REFESH_AIRSETTING_SUCCESS';
export const REFESH_AIRSETTING_FAILED = 'REFESH_AIRSETTING_FAILED';

export const REFESH_AIRTEMP ='REFESH_AIRTEMP';
export const REFESH_AIRTEMP_SUCCESS = 'REFESH_AIRTEMP_SUCCESS';
export const REFESH_AIRTEMP_FAILED = 'REFESH_AIRTEMP_FAILED';

// api pdu
export const REFESH_PDU ='REFESH_PDU';
export const REFESH_PDU_SUCCESS = 'REFESH_PDU_SUCCESS';
export const REFESH_PDU_FAILED = 'REFESH_PDU_FAILED';

export const REFESH_PDUPOWER ='REFESH_PDUPOWER';
export const REFESH_PDUPOWER_SUCCESS = 'REFESH_PDUPOWER_SUCCESS';
export const REFESH_PDUPOWER_FAILED = 'REFESH_PDUPOWER_FAILED';

// api smoke
export const REFESH_SMOKE ='REFESH_SMOKE';
export const REFESH_SMOKE_SUCCESS = 'REFESH_SMOKE_SUCCESS';
export const REFESH_SMOKE_FAILED = 'REFESH_SMOKE_FAILED';

// api door
export const REFESH_DOOR ='REFESH_DOOR';
export const REFESH_DOOR_SUCCESS = 'REFESH_DOOR_SUCCESS';
export const REFESH_DOOR_FAILED = 'REFESH_DOOR_FAILED';

// api Leak
export const REFESH_LEAK ='REFESH_LEAK';
export const REFESH_LEAK_SUCCESS = 'REFESH_LEAK_SUCCESS';
export const REFESH_LEAK_FAILED = 'REFESH_LEAK_FAILED';

// api Fan
export const REFESH_FAN ='REFESH_FAN';
export const REFESH_FAN_SUCCESS = 'REFESH_FAN_SUCCESS';
export const REFESH_FAN_FAILED = 'REFESH_FAN_FAILED';

// api control Fan
export const CONTROL_FAN ='CONTROL_FAN';
export const CONTROL_FAN_SUCCESS = 'CONTROL_FAN_SUCCESS';
export const CONTROL_FAN_FAILED = 'CONTROL_FAN_FAILED';

// api main
export const REFESH_MAIN ='REFESH_MAIN';
export const REFESH_MAIN_SUCCESS = 'REFESH_MAIN_SUCCESS';
export const REFESH_MAIN_FAILED = 'REFESH_MAIN_FAILED';

// api all_erea
export const REFESH_ALL_AREA ='REFESH_ALL_AREA';
export const REFESH_ALL_AREA_SUCCESS = 'REFESH_ALL_AREA_SUCCESS';
export const REFESH_ALL_AREA_FAILED = 'REFESH_ALL_AREA_FAILED';

// api house_erea
export const REFESH_HOUSE_AREA ='REFESH_HOUSE_AREA';
export const REFESH_HOUSE_AREA_SUCCESS = 'REFESH_HOUSE_AREA_SUCCESS';
export const REFESH_HOUSE_AREA_FAILED = 'REFESH_HOUSE_AREA_FAILED';

// api fish_lake_erea
export const REFESH_FISH_LAKE_AREA ='REFESH_FISH_LAKE_AREA';
export const REFESH_FISH_LAKE_AREA_SUCCESS = 'REFESH_FISH_LAKE_AREA_SUCCESS';
export const REFESH_FISH_LAKE_AREA_FAILED = 'REFESH_FISH_LAKE_AREA_FAILED';

// api solar_01_erea
export const REFESH_SOLAR01_AREA ='REFESH_SOLAR01_AREA';
export const REFESH_SOLAR01_AREA_SUCCESS = 'REFESH_SOLAR01_AREA_SUCCESS';
export const REFESH_SOLAR01_AREA_FAILED = 'REFESH_SOLAR01_AREA_FAILED';

// api solar_02_erea
export const REFESH_SOLAR02_AREA ='REFESH_SOLAR02_AREA';
export const REFESH_SOLAR02_AREA_SUCCESS = 'REFESH_SOLAR02_AREA_SUCCESS';
export const REFESH_SOLAR02_AREA_FAILED = 'REFESH_SOLAR02_AREA_FAILED';