"""empty message

Revision ID: dd480d087434
Revises: 
Create Date: 2020-11-11 16:38:41.588420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd480d087434'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spm91table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=True),
    sa.Column('frequency', sa.Float(), nullable=True),
    sa.Column('voltage', sa.Float(), nullable=True),
    sa.Column('current', sa.Float(), nullable=True),
    sa.Column('power', sa.Float(), nullable=True),
    sa.Column('enegry', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spm93model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=True),
    sa.Column('voltage_pa', sa.Float(), nullable=True),
    sa.Column('voltage_pb', sa.Float(), nullable=True),
    sa.Column('voltage_pc', sa.Float(), nullable=True),
    sa.Column('current_pa', sa.Float(), nullable=True),
    sa.Column('current_pb', sa.Float(), nullable=True),
    sa.Column('current_pc', sa.Float(), nullable=True),
    sa.Column('frequency', sa.Float(), nullable=True),
    sa.Column('totalapparentpower', sa.Float(), nullable=True),
    sa.Column('totalactiveennegry', sa.Float(), nullable=True),
    sa.Column('totalreactiveennegry', sa.Float(), nullable=True),
    sa.Column('activepower_pa', sa.Float(), nullable=True),
    sa.Column('activepower_pb', sa.Float(), nullable=True),
    sa.Column('activepower_pc', sa.Float(), nullable=True),
    sa.Column('totalactivepower', sa.Float(), nullable=True),
    sa.Column('reactivepower_pa', sa.Float(), nullable=True),
    sa.Column('reactivepower_pb', sa.Float(), nullable=True),
    sa.Column('reactivepower_pc', sa.Float(), nullable=True),
    sa.Column('totalreactivepower', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userlogtable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('operator', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('userlogtable')
    op.drop_table('spm93model')
    op.drop_table('spm91table')
    # ### end Alembic commands ###
